GET https://localhost:5001/api/vehicles HTTP/1.1

###

GET https://localhost:5001/api/vehicles HTTP/1.1
Accept: "application/application/xml"

###

GET https://localhost:5001/api/vehicles/10 HTTP/1.1

###

POST https://localhost:5001/api/vehicles HTTP/1.1
content-type: application/json

{
    "Model": "Mazda",
    "Vin": "645645654645654645",
    "ProductionYear": 2000
}

###
PUT https://localhost:5001/api/vehicles/10 HTTP/1.1
content-type: application/json

{
    "Id": 10,
    "Model": "Mazda",
    "Vin": "645645654645654645",
    "ProductionYear": 2000
}

###

DELETE https://localhost:5000/api/vehicles/10 HTTP/1.1

